### PR TITLE
fix: Fix CI; update deps

### PR DESCRIPTION
**Pull request by last-partizan**

### CODE REVIEW

**Comment by last-partizan** [comment]
I fixed some type errors after pyright update, but there's some `Mismatch between signature of __new__ and __init__` left.

But, that's better that completely broken ci :)

**Comment by last-partizan** [comment]
And bson/pymongo already have typing, so i removed them from here.

**Comment by sbdchd** [comment]
Looks good, thank you for removing bson and pymongo, good to hear they have integrated type stubs!!

**Comment by sbdchd** [comment]
CI is a lil angry:


```
+ [[ -n true ]]
+ black --check .
would reformat /home/circleci/project/mongoengine-stubs/base.pyi
would reformat /home/circleci/project/typings/mongoengine/base.pyi

Oh no! 💥 💔 💥
2 files would be reformatted, 20 files would be left unchanged.

Exited with code exit status 1
```

**Comment by last-partizan** [comment]
All green, but that's a surprise, there should be 4 errors related to `error: Mismatch between signature of __new__ and __init__`

Don't merge this yet, i'll look into it.

**Comment by last-partizan** [comment]
Updated pyright, now it correctly reports those 4 errors.

**Comment by last-partizan** [comment]
Fixed it, now it's ready to merge @sbdchd ;)

**Review by sbdchd — APPROVED** [review]

**Comment by sbdchd** [comment]
Thank you!!

**Pull request merged**
